#!/bin/bash
# Extract archives:
# *.tar, *.tgz, *.tar.gz, *.tar.bz, *.tar.bz2, *.tar.xz, *.zip

OUT_FILE="${1%.*}"

case $1 in
	*.zip)
		unzip "$1" -d "$OUT_FILE"
		;;
	*.tar)
		tar xvf "$1"
		;;
	*.tgz|*.tar.gz)
		tar xvzf "$1"
		;;   
    *.tar.bz)
		bzip -cd "$1" | tar xvf -
		;;
    *.tar.bz2)
		tar xvjf "$1" bzip2 -cd *.bz2 | tar xvf -
		;;
    *.tar.xz)
		tar xvJf "$1" xz -cd *.xz | tar xvf -
		;;
    *) 
    	echo 'Usage: extract [archive]'	
    	;;
esac
